# Uncomment this line to define a global platform for your project
platform :ios, ‘9.2’
# Uncomment this line if you're using Swift
use_frameworks!

target 'HelloWorld' do
    pod 'XcodeServerSDK'
end

target 'HelloWorldTests' do

end

target 'HelloWorldUITests' do

end

